#!/usr/bin/env bash

echo "Release:Optimize for speed:release"
echo "Debug Optimized:Optimize for speed and include debug symbols:debugoptimized"
echo "Debug:Include debug symbols, etc:debug"
echo "Deterministic:Create a deterministic debug build. Uses libunthread to replace pthreads.:deterministic"
