// Compile-time errors
STATUS(OK, "ok")
STATUS(NONE, "")
STATUS(TERM, "FIBER TERMINATED")
STATUS(PANIC, "A FATAL ERROR OCCURRED")
STATUS(MALFORMED_TOKEN, "UNRECOGNIZED TOKEN")
STATUS(MALFORMED_STRING, "MALFORMED STRING VALUE")
STATUS(MALFORMED_EXPRESSION, "MALFORMED EXPRESSION")
STATUS(MALFORMED_BINDING, "MALFORMED BINDING")
STATUS(UNEXPECTED_EOF, "UNEXPECTED END OF FILE")
STATUS(TOO_MANY_LOCALS, "BLOCKS CANNOT HAVE MORE THAN 255 LOCALS")
STATUS(TOO_MANY_UPVALUES, "BLOCKS CANNOT CAPTURE MORE THAN 255 VARIABLES")
STATUS(UNBOUND_SYMBOL, "SYMBOLS MUST BE BOUND BEFORE THEY CAN BE REFERENCED")
STATUS(MISSING_INITIALIZER, "VARIABLES MUST BE INITIALIZED")

// Run-time errors
STATUS(TYPE_MISMATCH, "Type Mismatch")
STATUS(SPECIALIZATION_MISSING, "Missing Specialization")
STATUS(OVERFLOW, "Fiber stack overflow")
