// Compile-time errors
STATUS(OK, "ok")
STATUS(NONE, "")
STATUS(TERM, "Fiber terminated")
STATUS(PANIC, "A fatal error occurred")
STATUS(MALFORMED_TOKEN, "Unrecognized token")
STATUS(MALFORMED_STRING, "Malformed string")
STATUS(MALFORMED_RECORD_PAIR, "Malformed pair in record expression")
STATUS(MALFORMED_SEND, "Malformed send expression")
STATUS(MISSING_SEPARATOR, "Missing Separator")
STATUS(UNEXPECTED_TOKEN, "Unexpected token")
STATUS(UNEXPECTED_EOF, "Unexpected end of file")
STATUS(TOO_MANY_LOCALS, "Blocks cannot have more than 255 locals")
STATUS(TOO_MANY_UPVALUES, "Blocks cannot capture more than 255 locals")
STATUS(TOO_MANY_PARAMETERS, "Blocks cannot have more than 16 parameters")
STATUS(TOO_MANY_ARGUMENTS, "Blocks calls cannot have more than 16 arguments")
STATUS(TOO_MANY_RETURN_VALUES, "Blocks cannot return more than 16 values")
STATUS(TOO_MANY_EXPRESSIONS, "Expected fewer expressions")
STATUS(REFERENCE_BEFORE_INITIALIZE, "Uninitialized variable")
STATUS(UNBOUND_SYMBOL, "Symbols must be bound before they can be referenced")
STATUS(MALFORMED_ASSIGNMENT, "Malformed assignment expression")
STATUS(MISSING_END, "Block needs a corresponding 'end'")
STATUS(MISSING_INITIALIZER, "Variables must be initialized")

// Run-time errors
STATUS(TYPE_MISMATCH, "Type Mismatch")
STATUS(INVALID_SHIFT_AMOUNT, "Invalid Shift Amount")
STATUS(SPECIALIZATION_MISSING, "Missing Specialization")
STATUS(OVERFLOW, "Reached Maximum Call Depth")
