name: Release static binaries

#
# This action builds, tests, and releases new versions of gab.
#
# Currently, all windows builds are disabled.
#
# This is because there are some c-abi issues with zig cc, and these affect
# only the windows platform. Until these bugs are fixed in zig cc, Gab will not
# support windows.
#
# (Unless I feel ike refactoring all the code that is using these abi features - passing structs as arguments).

on:
  push:
    branches: [ "main" ]

env:
  version: 0.0.3
  GH_TOKEN: ${{ github.token }}

jobs:
  build_artifacts:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-linux-gnu
          - x86_64-macos-none
          # - x86_64-windows-gnu
          - aarch64-linux-gnu
          - aarch64-macos-none
          # - aarch64-windows-gnu
        build_type:
          - release
          - debugoptimized

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

      # Zig is the C compiler used by the build system
    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: 0.14.0

      # Build system depends on Go
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

      # Build system tool
    - name: Install Clide
      run: go install github.com/TeddyRandby/clide@latest

    - name: Configure
      run: clide configure -b='${{ matrix.build_type }}' -t='${{ matrix.target }}'

    - name: Build
      run: clide build

    - name: Upload Binary Artifact
      uses: pyTooling/upload-artifact@v4
      with:
        name: 'gab-${{ matrix.build_type }}-${{ matrix.target }}'
        path: 'build-${{ matrix.target }}/gab'

    - name: Collect modules
      run: cp build-${{ matrix.target }}/mod/* mod

    - name: Upload Module Artifacts
      uses: pyTooling/upload-artifact@v4
      with:
        name: 'gab-${{ matrix.build_type }}-${{ matrix.target }}-modules'
        path: mod

  run_tests:
    strategy:
      matrix:
        build_type:
          - release
        os: 
          - ubuntu-latest
          - macos-latest
          # - windows-latest
        include:
          - os: ubuntu-latest
            target: x86_64-linux-gnu
            cmd: ./build-x86_64-linux-gnu/gab
          - os: macos-latest
            target: x86_64-macos-none
            cmd: ./build-x86_64-macos-none/gab
          # - os: windows-latest
          #   target: x86_64-windows-gnu
          #   cmd: .\build-x86_64-windows-gnu\gab

    runs-on: ${{ matrix.os }}
    needs: build_artifacts

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download Binary
        uses: pyTooling/download-artifact@v4
        with:
          name: 'gab-${{ matrix.build_type }}-${{ matrix.target }}'

      - name: Download Modules
        uses: pyTooling/download-artifact@v4
        with:
          name: gab-${{ matrix.build_type }}-${{ matrix.target }}-modules

      # - name: Make the binary executable (win)
      #   if: ${{ contains(matrix.target, 'windows') }}
      #   run: |
      #     move gab gab.exe
      #     where.exe "gab"
      #     Get-Command ".\gab"

      # - name: Run Smallest Hello World
      #   run: ${{ matrix.cmd }} exec -e "'hello world!'"

      # - name: Run Hello World
      #   run: ${{ matrix.cmd }} exec "'hello world!' .println"

      - name: Run tests
        run: ${{ matrix.cmd }} run test

  create_release:
    runs-on: ubuntu-latest
    needs: run_tests

    permissions: write-all

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Check for existing tag
        continue-on-error: true
        id: tag_check
        run: git ls-remote --tags | grep '${{ env.version }}' 

      # Create a release if we didn't find an existing tag
      - name: Create Release
        if: ${{ steps.tag_check.outcome == 'failure' }}
        run:  gh release create -R '${{ github.repository }}' '${{ env.version }}' --generate-notes

  release_artifacts:
    runs-on: ubuntu-latest
    needs: create_release

    permissions: write-all

    strategy:
      matrix:
        target:
          - x86_64-linux-gnu
          - x86_64-macos-none
          # - x86_64-windows-gnu
          - aarch64-linux-gnu
          - aarch64-macos-none
          # - aarch64-windows-gnu
        build_type:
          - release
          - debugoptimized

    steps:
      # Download artifacts created by the build step
      - name: Download Binary
        uses: pyTooling/download-artifact@v4
        with:
          name: 'gab-${{ matrix.build_type }}-${{ matrix.target }}'

      - name: Download Modules
        uses: pyTooling/download-artifact@v4
        with:
          name: 'gab-${{ matrix.build_type }}-${{ matrix.target }}-modules'

      - name: Create Module Archive
        run: tar -cvzf 'gab-${{ matrix.build_type }}-${{ matrix.target }}-modules' mod/*
      
      - name: Rename binary
        run: mv build-${{ matrix.target }}/gab 'gab-${{ matrix.build_type }}-${{ matrix.target }}'

      - name: Attach binary to release
        run: gh release upload -R '${{ github.repository }}' '${{ env.version }}' 'gab-${{ matrix.build_type }}-${{ matrix.target }}' || exit 0

      - name: Attach modules to release
        run: gh release upload -R '${{ github.repository }}' '${{ env.version }}' 'gab-${{ matrix.build_type }}-${{ matrix.target }}-modules' || exit 0
