name: Build and test pull requests

#
# This action tests pull requests.
#
# Currently, all windows builds are disabled.
#
# This is because there are some c-abi issues with zig cc, and these affect
# only the windows platform. Until these bugs are fixed in zig cc, Gab will not
# support windows.
#
# (Unless I feel ike refactoring all the code that is using these abi features - passing structs as arguments).

on:
  pull_request:
    branches: [ "main" ]

env:
  version: 0.0.5
  GH_TOKEN: ${{ github.token }}

jobs:
  build_artifacts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

      # Zig is the C compiler used by the build system
    - name: Setup Zig
      uses: mlugg/setup-zig@v2
      with:
        version: master

      # Build system depends on Go
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - uses: actions/setup-node@v5
      with:
        node-version: 24

      # Build system tool
    - name: Install Clide
      run: go install github.com/TeddyRandby/clide@latest

    - name: Configure
      run: clide configure -t='x86_64-linux-gnu x86_64-macos-none aarch64-linux-gnu aarch64-macos-none' -b='release'

    - name: Build
      run: clide build

    - name: Move native modules
      run: |
        mkdir -p github.com/gab-language/cgab@${{ env.version }}/mod
        cp build-*/mod/* github.com/gab-language/cgab@${{ env.version }}/mod

    - name: Move built gab binaries into install directory
      run: |
          mkdir -p ~/gab
          mkdir -p ~/gab/${{ env.version }}-x86_64-linux-gnu
          mkdir -p ~/gab/${{ env.version }}-aarch64-linux-gnu
          mkdir -p ~/gab/${{ env.version }}-x86_64-macos-none
          mkdir -p ~/gab/${{ env.version }}-aarch64-macos-none
          mkdir -p ~/gab/${{ env.version }}-x86_64-windows-gnu
          mkdir -p ~/gab/${{ env.version }}-aarch64-windows-gnu

          cp build-x86_64-linux-gnu/gab/gab ~/gab/${{ env.version }}-x86_64-linux-gnu
          cp build-aarch64-linux-gnu/gab/gab ~/gab/${{ env.version }}-aarch64-linux-gnu
          cp build-x86_64-macos-none/gab/gab ~/gab/${{ env.version }}-x86_64-macos-none
          cp build-aarch64-macos-none/gab/gab ~/gab/${{ env.version }}-aarch64-macos-none
          cp build-x86_64-windows-gnu/gab/gab ~/gab/${{ env.version }}-x86_64-windows-gnu
          cp build-aarch64-windows-gnu/gab/gab ~/gab/${{ env.version }}-aarch64-windows-gnu

    - name: Create bundles
      run: |
         ./build-x86_64-linux-gnu/gab/gab build -n -t x86_64-linux-gnu   < bundle
         ./build-x86_64-linux-gnu/gab/gab build -n -t aarch64-linux-gnu  < bundle
         ./build-x86_64-linux-gnu/gab/gab build -n -t x86_64-macos-none  < bundle
         ./build-x86_64-linux-gnu/gab/gab build -n -t aarch64-macos-none < bundle
         ./build-x86_64-linux-gnu/gab/gab build -n -t x86_64-windows-gnu  < bundle
         ./build-x86_64-linux-gnu/gab/gab build -n -t aarch64-windows-gnu < bundle

    # For this step, gab needs to know where the binaries are to cross-compile
    # the executables.
    - name: Create Cross-Compiled Test binary
      run: |
         ./build-x86_64-linux-gnu/gab/gab build -n -t x86_64-linux-gnu test < bundle
         ./build-x86_64-linux-gnu/gab/gab build -n -t aarch64-linux-gnu test < bundle
         ./build-x86_64-linux-gnu/gab/gab build -n -t x86_64-macos-none test < bundle
         ./build-x86_64-linux-gnu/gab/gab build -n -t aarch64-macos-none test < bundle
         ./build-x86_64-linux-gnu/gab/gab build -n -t x86_64-windows-gnu test < bundle
         ./build-x86_64-linux-gnu/gab/gab build -n -t aarch64-windows-gnu test < bundle

    - name: Upload x86_64-linux-gnu Binary Artifact
      uses: pyTooling/upload-artifact@v4
      with:
        name: 'gab-x86_64-linux-gnu-release'
        path: 'build-x86_64-linux-gnu/gab'

    - name: Upload x86_64-linux-gnu Bundle Artifact
      uses: pyTooling/upload-artifact@v4
      with:
        name: 'cgab-${{ env.version }}-x86_64-linux-gnu'
        path: 'cgab-${{ env.version }}-x86_64-linux-gnu'

    - name: Upload x86_64-linux-gnu Test Executable Artifact
      uses: pyTooling/upload-artifact@v4
      with:
        name: 'test.cgab-${{ env.version }}-x86_64-linux-gnu.exe'
        path: 'test.cgab-${{ env.version }}-x86_64-linux-gnu.exe'

    - name: Upload aarch64-linux-gnu Binary Artifact
      uses: pyTooling/upload-artifact@v4
      with:
        name: 'gab-aarch64-linux-gnu-release'
        path: 'build-aarch64-linux-gnu/gab'

    - name: Upload aarch64-linux-gnu Bundle Artifact
      uses: pyTooling/upload-artifact@v4
      with:
        name: 'cgab-${{ env.version }}-aarch64-linux-gnu'
        path: 'cgab-${{ env.version }}-aarch64-linux-gnu'

    - name: Upload aarch64-linux-gnu Test Executable Artifact
      uses: pyTooling/upload-artifact@v4
      with:
        name: 'test.cgab-${{ env.version }}-aarch64-linux-gnu.exe'
        path: 'test.cgab-${{ env.version }}-aarch64-linux-gnu.exe'

    - name: Upload x86_64-macos-none Binary Artifact
      uses: pyTooling/upload-artifact@v4
      with:
        name: 'gab-x86_64-macos-none-release'
        path: 'build-x86_64-macos-none/gab'

    - name: Upload x86_64-macos-none Bundle Artifact
      uses: pyTooling/upload-artifact@v4
      with:
        name: 'cgab-${{ env.version }}-x86_64-macos-none'
        path: 'cgab-${{ env.version }}-x86_64-macos-none'

    - name: Upload x86_64-macos-none Test Executable Artifact
      uses: pyTooling/upload-artifact@v4
      with:
        name: 'test.cgab-${{ env.version }}-x86_64-macos-none.exe' 
        path: 'test.cgab-${{ env.version }}-x86_64-macos-none.exe'

    - name: Upload aarch64-macos-none Binary Artifact
      uses: pyTooling/upload-artifact@v4
      with:
        name: 'gab-aarch64-macos-none-release'
        path: 'build-aarch64-macos-none/gab'

    - name: Upload aarch64-macos-none Bundle Artifact
      uses: pyTooling/upload-artifact@v4
      with:
        name: 'cgab-${{ env.version }}-aarch64-macos-none' 
        path: 'cgab-${{ env.version }}-aarch64-macos-none'

    - name: Upload aarch64-macos-none Test Executable Artifact
      uses: pyTooling/upload-artifact@v4
      with:
        name: 'test.cgab-${{ env.version }}-aarch64-macos-none.exe' 
        path: 'test.cgab-${{ env.version }}-aarch64-macos-none.exe'

    - name: Upload x86_64-windows-gnu Binary Artifact
      uses: pyTooling/upload-artifact@v4
      with:
        name: 'gab-x86_64-windows-gnu-release'
        path: 'build-x86_64-windows-gnu/gab'

    - name: Upload x86_64-windows-gnu Bundle Artifact
      uses: pyTooling/upload-artifact@v4
      with:
        name: 'cgab-${{ env.version }}-x86_64-windows-gnu'
        path: 'cgab-${{ env.version }}-x86_64-windows-gnu'

    - name: Upload x86_64-windows-gnu Test Executable Artifact
      uses: pyTooling/upload-artifact@v4
      with:
        name: 'test.cgab-${{ env.version }}-x86_64-windows-gnu.exe'
        path: 'test.cgab-${{ env.version }}-x86_64-windows-gnu.exe'

    - name: Upload aarch64-windows-gnu Binary Artifact
      uses: pyTooling/upload-artifact@v4
      with:
        name: 'gab-aarch64-windows-gnu-release'
        path: 'build-aarch64-windows-gnu/gab'

    - name: Upload aarch64-windows-gnu Bundle Artifact
      uses: pyTooling/upload-artifact@v4
      with:
        name: 'cgab-${{ env.version }}-aarch64-windows-gnu'
        path: 'cgab-${{ env.version }}-aarch64-windows-gnu'

    - name: Upload aarch64-windows-gnu Test Executable Artifact
      uses: pyTooling/upload-artifact@v4
      with:
        name: 'test.cgab-${{ env.version }}-aarch64-windows-gnu.exe'
        path: 'test.cgab-${{ env.version }}-aarch64-windows-gnu.exe'

  run_tests:
    strategy:
      matrix:
        build_type:
          - release
        os: 
          - ubuntu-latest
          - macos-latest
          - windows-latest
        include:
          - os: ubuntu-latest
            target: x86_64-linux-gnu
            cmd: ./build-x86_64-linux-gnu/gab/gab
          - os: macos-latest
            target: aarch64-macos-none
            cmd: ./build-aarch64-macos-none/gab/gab
          - os: windows-latest
            target: x86_64-windows-gnu
            cmd: .\build-x86_64-windows-gnu\gab

    runs-on: ${{ matrix.os }}
    needs: build_artifacts

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download Binary
        uses: pyTooling/download-artifact@v4
        with:
          name: 'gab-${{ matrix.target }}-${{ matrix.build_type }}'

      - name: Download Modules
        uses: pyTooling/download-artifact@v4
        with:
          name: cgab-${{ env.version }}-${{ matrix.target }}

      - name: Download Cross-Compiled Binary
        uses: pyTooling/download-artifact@v4
        with:
          name: test.cgab-${{ env.version }}-${{ matrix.target }}.exe

      - name: Unzip & Install Modules
        run: |
          mkdir -p ~/gab/${{ env.version }}-${{ matrix.target }}/github.com/gab-language/cgab@${{ env.version }}/mod
          unzip -o cgab-${{ env.version }}-${{ matrix.target }} -d ~/gab/${{ env.version }}-${{ matrix.target }}

      - name: Make the binary executable (win)
        if: ${{ contains(matrix.target, 'windows') }}
        run: |
          move .\build-${{ matrix.target}}\gab\gab .\build-${{ matrix.target }}\gab\gab.exe

      - name: DEBUG - List files
        run: ls -al

      - name: Welcome
        run: ${{ matrix.cmd }}

      - name: Run Smallest Hello World
        run: ${{ matrix.cmd }} exec "'hello world!'"

      - name: Run Hello World
        run: ${{ matrix.cmd }} exec -m github.com/gab-language/cgab@0.0.5:Io "'hello world!' .println"

      - name: Run tests
        run: ${{ matrix.cmd }} run test

      - name: Run cross-compiled tests bundle
        run: ./test.cgab-${{ env.version }}-${{ matrix.target }}.exe

      - name: Gab Build Bundle
        run: |
          ${{ matrix.cmd }} build test < bundle

      - name: Run tests bundle
        run: ./test.cgab-${{ env.version }}-${{ matrix.target }}.exe
